### PR TITLE
Make `location` field optional

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by koslib** [comment]
hello @xliiv and thanks for your contribution! I need to ask you something first so that I have a better understanding of your effort and also update the README file accordingly, if needed.
As I can see, it will still try to get the coordinates out of the request, except it fails for any reason in the `ip_to_cordinates()` method, right? 
Would that make sense to let the django developer actually choose if he would like to include that info or not, in the settings? 
Thanks in advance!

**Comment by ghost** [comment]
That's right. However I'm not sure what you want me to do by saying ".. choose if he would like to include that info or not", so please be more specific :)
I'll update README when we settle my change.

In addition, I'd recommend changing name to something without dash (-), because dash it's invalid python module char.
```
> vf tmp -p python2.7
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /home/xliiv/.virtualenvs/tempenv-3bcc690959cd/bin/python2.7
Also creating executable in /home/xliiv/.virtualenvs/tempenv-3bcc690959cd/bin/python
Installing setuptools, pip, wheel...done.
[I] [18:57:40] xliiv@alef /home/xliiv (0) 
> pip install django-traffic
Collecting django-traffic
Installing collected packages: django-traffic
Successfully installed django-traffic-1.0.0
[I] [18:57:50] xliiv@alef /home/xliiv (0) 
> python
Python 2.7.12+ (default, Sep 17 2016, 12:08:02) 
[GCC 6.2.0 20160914] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import django-traffic
  File "<stdin>", line 1
    import django-traffic
                 ^
SyntaxError: invalid syntax
>>> from django-traffic import middleware
  File "<stdin>", line 1
    from django-traffic import middleware
               ^
SyntaxError: invalid syntax
>>> 
```

**Comment by koslib** [comment]
@xliiv Oh yes sure I'll explain, nothing too complex, maybe add a `settings.py` var `INCLUDE_GEO_INFO` defaulting to `True`, so that the developer would be able to choose if he'd like also geo data to be sent in ElasticSearch or not. Would that make sense, does it offer any value? 

Regarding the name, you're right, can you please go ahead and change it to `django_traffic` (with underscore) in this PR? 

Thanks in advance!

**Comment by ghost** [comment]
Ok, I added `LOG_WITHOUT_LOCATION` and set it to `False` so that it works exactly the same as before this change.
I'm not gonna change name now, maybe some other time.. .

**Comment by koslib** [comment]
ok! I'll merge the PR and work on this myself until the next version! Thanks!

**Pull request merged**
